# kubectl --kubeconfig=c:\Users\User\_myWork\Kloster\Kloster1.yaml --namespace=ya2 get pods
# 
# kubectl --kubeconfig=c:\Users\User\_myWork\Kloster\Kloster1.yaml --namespace=ya2 exec -it mysql-5f46cd7d5c-jz9xj sh
# create database Games

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ya2
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mysql01
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Hejsan123"
        - name: MYSQL_DATABASE
          value: "Games"
        volumeMounts:
        - name: mysqldb
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqldb
        persistentVolumeClaim:
          claimName: pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ya2
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP